sudo: required
services:
  - docker

before_install:
  - docker build -t arthur/elasticbeanstalk-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elasticbeanstalk-docker-react npm run test